name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: devops_db
          POSTGRES_USER: devops_user
          POSTGRES_PASSWORD: devops_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_NAME: devops_db
      DB_USER: devops_user
      DB_PASSWORD: devops_pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test

      - name: Build Docker image
        run: docker build -t samueljb1/devops-python-app .

      - name: Log in to DockerHub
        run: echo "${{ devsutest }}" | docker login -u samueljb1 --password-stdin

      - name: Push image to DockerHub
        run: docker push samueljb1/devops-python-app
